# Generated by Django 2.0 on 2018-06-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likecount',
            options={'verbose_name': '点赞统计', 'verbose_name_plural': '点赞统计'},
        ),
        migrations.AlterModelOptions(
            name='likerecord',
            options={'verbose_name': '点赞记录', 'verbose_name_plural': '点赞记录'},
        ),
    ]
