# Generated by Django 2.0 on 2018-06-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_record', '0002_auto_20180606_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'verbose_name': '阅读详细', 'verbose_name_plural': '阅读详细'},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '阅读统计', 'verbose_name_plural': '阅读统计'},
        ),
    ]
